### PR TITLE
Security upgrade

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by krishnabvkr — APPROVED** [review]

**Review by malibuworkcrew — APPROVED** [review]

**Review by malibuworkcrew — COMMENTED** [review]
We shouldn't  commit internal endpoints to the public repo. What I ended up doing to get around this was have our internal jenkins job add the internal artifactory via a script. Check out this commit for wookiee-akka-http, you should be able to copy over those changes to here to get the same effect: https://github.com/oracle/wookiee-akka-http/commit/cc0f5e6b265fc698cb1d9b6a7cb61a15a496695f

**Review by Kraagen — CHANGES_REQUESTED** [review]
See Spencer's comment. You can't add an internal repository to public code.

**Comment by malibuworkcrew** [comment]
Looks good!

**Review by Kraagen — APPROVED** [review]
Approving as an interim workaround to our build issues. This should not be considered a final solution and work should continue to clean up the build and publishing process.

**Pull request merged**
